{% set name = "isce2" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/isce-framework/isce2/archive/v{{ version }}.tar.gz
    sha256: 151cdfefe68227af40875147f89691a668508fb4345e8fb7030eef914f4b25e6
    folder: isce2

build:
  number: 0
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - cython
  host:
    - cython
    - python
    - numpy
    - hdf5
    - libgdal
    - fftw
    - opencv
    - openmotif-dev
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - scipy
    - h5py
    - opencv
    - gdal
    - requests

test:
  imports:
    - isce
  commands:
    - topsApp.py --help --steps
    - stripmapApp.py --help --steps
    - dem.py --help
    - isce2gis.py -h
    - imageMath.py -h
    - alos2App.py --help --steps
    - alos2burstApp.py --help --steps
    - $PYTHON {{ RECIPE_DIR }}/run_test.py
    - mdx

about:
  home: http://github.com/isce-framework/isce2
  license: Apache-2.0
  license_family: Apache
  license_file: isce2/LICENSE-2.0.txt
  summary: InSAR Scientific Computing Environment

  description: |
    InSAR Scientific Computing Environment (ISCE) is a framework designed
    for processing Synthetic Aperture Radar (SAR) And Interferometric SAR
    (InSAR) data. Currently, ISCE supports processing of data acquired by
    following platforms - ALOS, ALOS2, COSMO-SkyMed, EnviSAT, ERS,
    KOMPSAT5,  RadarSAT2, RISAT1, Sentinel1, TerraSAR-X, Tandem-X, 
    and UAVSAR. ISCE can also read some SICD format data.

  doc_url: https://github.com/isce-framework/isce2-docs
  dev_url: https://github.com/isce-framework/isce2

extra:
  recipe-maintainers:
    - bryanvriel
    - piyushrpt
    - rtburns-jpl
