{% set name = "isce2" %}
{% set version = "2.3.3" %}
{% set autoriftver = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    - url: https://github.com/isce-framework/isce2/archive/v{{ version }}.tar.gz
      sha256: f093086846426b855aa279bcee7de59668587faf1bd8324f6546b216578bfea6
      folder: isce2

    - url: https://github.com/leiyangleon/autoRIFT/archive/v{{ autoriftver }}.tar.gz
      sha256: 0fb07d147c9ea72417aea82ff289d668b5d2c3182b508a7f60b1117f2981502f
      folder: autorift

build:
  number: 1
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - cython
    - scons
    - hdf5
    - libgdal
    - fftw
    - opencv 3.4
    - openmotif-dev  # [linux]
    - xorg-libxt     # [linux]
    - xorg-libxft    # [linux]
    - xorg-libxmu    # [linux]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - hdf5
    - h5py
    - opencv 3.4
    - gdal
    - libgdal
    - fftw
    - xorg-libxt  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxdmcp  # [linux]
    - openmotif  # [linux]
    - requests

test:
  imports:
    - isce
  commands:
    - ISCEHOME=`$PYTHON -c "import isce, os; print(os.path.dirname(isce.__file__))" | tail -n 1`
    - ${ISCEHOME}/applications/topsApp.py --help --steps
    - ${ISCEHOME}/applications/stripmapApp.py --help --steps
    - ${ISCEHOME}/applications/dem.py --help
    - ${ISCEHOME}/applications/isce2gis.py -h
    - ${ISCEHOME}/applications/imageMath.py -h
    - ${ISCEHOME}/applications/alos2App.py --help --steps
    - ${ISCEHOME}/applications/alos2burstApp.py --help --steps
    - ${ISCEHOME}/applications/testautoRIFT.py -h
    - ${ISCEHOME}/applications/testautoRIFT_ISCE.py -h
    - python {{ RECIPE_DIR }}/run_test.py
    - ${ISCEHOME}/bin/mdx    # [linux]

about:
  home: http://github.com/isce-framework/isce2
  license: Apache-2.0
  license_family: Apache
  license_file: isce2/LICENSE-2.0.txt
  summary: InSAR Scientific Computing Environment

  description: |
    InSAR Scientific Computing Environment (ISCE) is a framework designed
    for processing Synthetic Aperture Radar (SAR) And Interferometric SAR
    (InSAR) data. Currently, ISCE supports processing of data acquired by
    following platforms - ALOS, ALOS2, COSMO-SkyMed, EnviSAT, ERS,
    KOMPSAT5,  RadarSAT2, RISAT1, Sentinel1, TerraSAR-X, Tandem-X, 
    and UAVSAR. ISCE can also read some SICD format data.

  doc_url: https://github.com/isce-framework/isce2-docs
  dev_url: https://github.com/isce-framework/isce2

extra:
  recipe-maintainers:
    - BryanRiel
    - piyushrpt
    - rtburns-jpl
