{% set name = "isce2" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/isce-framework/isce2/archive/v{{ version }}.tar.gz
    sha256: 3b2be8efebb2fce40d9360c90670e02353719c3fdadfcb7cc280beb34fe2ab85
    folder: isce2
    patches:
      # Use LDFLAGS from conda build environment
      - env-ldflags.patch
      # Allow argument missmatch for gfortran
      - argument-missmatch.patch
      # Fix ` ld: in .../libs/libcosar.a(Cosar.hh), archive member 'Cosar.hh' with length 440 is not mach-o or llvm bitcode file`
      - cosar-sources.patch

build:
  number: 1
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy <2  # Pinned in conda_build_config.yml
    - cython
    - scons
    - hdf5
    - libgdal <3.11  # Pinned in conda_build_config.yml
    - fftw
    - opencv
    - libacl  # [linux]
    - libgl-devel  # [linux]
    - openmotif-dev
    - xorg-libxt
    - xorg-libxft
    - xorg-libxmu
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - scipy
    - h5py
    - gdal
    - xorg-libxt
    - xorg-libxft
    - xorg-libxmu
    - xorg-libxdmcp
    - openmotif
    - requests
    - zstd  # [osx]

test:
  imports:
    - isce
  commands:
    - ISCEHOME=`$PYTHON -c "import isce, os; print(os.path.dirname(isce.__file__))" | tail -n 1`
    - ${ISCEHOME}/applications/topsApp.py --help --steps
    - ${ISCEHOME}/applications/stripmapApp.py --help --steps
    - ${ISCEHOME}/applications/dem.py --help
    - ${ISCEHOME}/applications/isce2gis.py -h
    - ${ISCEHOME}/applications/imageMath.py -h
    - ${ISCEHOME}/applications/alos2App.py --help --steps
    - ${ISCEHOME}/applications/alos2burstApp.py --help --steps
    - python {{ RECIPE_DIR }}/run_test.py
    - ${ISCEHOME}/bin/mdx  # [not osx]

about:
  home: http://github.com/isce-framework/isce2
  license: Apache-2.0
  license_family: Apache
  license_file: isce2/LICENSE-2.0.txt
  summary: InSAR Scientific Computing Environment

  description: |
    InSAR Scientific Computing Environment (ISCE) is a framework designed
    for processing Synthetic Aperture Radar (SAR) And Interferometric SAR
    (InSAR) data. Currently, ISCE supports processing of data acquired by
    following platforms - ALOS, ALOS2, COSMO-SkyMed, EnviSAT, ERS,
    KOMPSAT5,  RadarSAT2, RISAT1, Sentinel1, TerraSAR-X, Tandem-X, 
    and UAVSAR. ISCE can also read some SICD format data.

  doc_url: https://github.com/isce-framework/isce2-docs
  dev_url: https://github.com/isce-framework/isce2

extra:
  recipe-maintainers:
    - jhkennedy
    - bryanvriel
    - piyushrpt
    - rtburns-jpl
