travis:
  secure:
    BINSTAR_TOKEN: nuaiSZ/8Ek8cIc8+Qwsp3qr4bZYvdXNlRE+3JxvsLGluDtJFfQ/sgNNMN5blU82En2zW3Mzf5QaPXw905wKLPAQLo4aV5622gxaMZNzXKx0rt6O2L2x7DwmYhI6IctTnTgkic876Sx+tfjJiLn+TxA3iXfb3mB9Ox0NeaaBPelFF71AGxrWuuUI0CgoOxddbU8Ji9bn75RPbEnTXk8/MiBw0G7bc7a+yJ1gkGLl1ZYDkSSMFUhWNH16N3BmpC6MtugJqH8tZ+2lddX8Oc1COKSAAdPMlKvkFFlbXR5yCKerEl3g08NRn9Wf7Zos3hiwaNGZuL3YtQEfxg2jV7OO/JZJiZ+AyxzyVVnjw6FdRok4szoaybocRLqsueFajt4eyKwxBzPVbwzQO1N36c7sw+Y/ot6g1iBfa8j2gfhrlewHBnujHIq6yLJNVakV6VjJEmgzOKwd4VteEBo8Vm4EvV8paLP42Iz8USvsXzRotMhSWropKrkKRXh5cEa2ArhhMfSpE2HKc1eztNxQ2G/AzoPDCEJHPu/T8KxVt1KAGHbRL4kUDiJCU/2RkXeIdkBf8byQT6qG89RYFi47jkxy9G09ByESDvpMOLXtlrGU9Ja0ghhRv68pKTZNhf1KlOGLoH+FtEzD9909u29v1ukNYSGDA9pjHZtGF8KXasgZ5YgI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
